export const resumeData = {
  profile: {
    name: "Eugene Belong",
    title: "Logistics & Operations Support Professional",
    location: "Davao City, Philippines",
    phone: "09673856254",
    email: "eugenebelong.va3@gmail.com",
    linkedin: "https://linkedin.com/in/eugene-belong-46b472393",
    linkedinDisplay: "linkedin.com/in/eugene-belong-46b472393",
    image: "https://media.licdn.com/dms/image/v2/D5635AQEXLiG0RIGMuQ/profile-framedphoto-shrink_200_200/B56ZwSmsg2IoAY-/0/1769838660007?e=1791057600&v=beta&t=czqDyD4b-YTA0CGSl8yb650arkvxPXib82P4immEaOU",
    coverImage: "https://media.licdn.com/dms/image/v2/D5616AQEarYJl6gGnzg/profile-displaybackgroundimage-shrink_350_1400/B56ZwSoGXnIYAY-/0/1769839029545?e=1792022400&v=beta&t=Hf02s5QoQqDVhCzhTvvqPGZHADrlvyYU6Hsk-S8dFe8",
  },

  summary:
    "Customer-focused Logistics & Operations Support professional with hands-on experience in logistics coordination, shipment tracking, order monitoring, and order reconciliation gained through sales, appointment-setting, and account management roles in the logistics, insurance, healthcare, and recruitment industries. Skilled in CRM data entry, client communication, lead generation, appointment scheduling, and cross-functional coordination with dispatch, fulfillment, and internal operations teams. Recognized for accuracy, reliability, and the ability to manage high-volume workflows in fast-paced, deadline-driven environments.",

  coreSkills: [
    "Logistics Coordination & Support",
    "Shipment Tracking & Monitoring",
    "Order Tracking & Order Reconciliation",
    "Route & Appointment Scheduling",
    "Dispatch Coordination",
    "Freight & Carrier Communication",
    "CRM Data Entry & Records Management",
    "Order Processing & Account Management",
    "Client Relations & Customer Service",
    "Lead Generation & Inside Sales (ISA/BDR/SDR)",
    "Talent Acquisition & Candidate Sourcing (ATS)",
    "Administrative & Operations Support",
    "Healthcare Support & Medical Billing",
    "Social Media Management",
    "Team Leadership",
  ],

  experience: [
    {
      role: "Data Management Specialist",
      company: "LeadPilot",
      date: "July 2026 – Present",
      location: "United States · Remote",
      bullets: [
        "Maintained the accuracy, organization, and integrity of customer and operational data within the GoHighLevel (GHL) CRM platform.",
        "Managed contact databases, imported and cleaned large datasets, eliminated duplicate records, and ensured all client information was up to date.",
        "Supported sales and marketing teams by organizing pipelines, tracking lead progress, assigning opportunities, and generating reports that improved decision-making and workflow efficiency.",
        "Created and updated custom fields, tags, workflows, and automations; monitored data quality and troubleshot CRM-related issues.",
        "Collaborated with different departments to optimize CRM processes, improve lead management, and maintain accurate reporting dashboards.",
      ],
      skills: ["GoHighLevel (GHL)", "CRM Management", "Data Cleaning", "Pipeline Management", "Workflow Automation", "Lead Management"],
    },
    {
      role: "Customer Service Specialist",
      company: "Tsunami Express Car Wash",
      date: "December 2024 – June 2026",
      location: "Lake Oswego, Oregon, United States",
      bullets: [
        "Delivered professional customer service in a fast-paced car wash environment, handling client inquiries, service requests, and account concerns.",
        "Managed inbound communications and resolved customer issues with accuracy and empathy.",
        "Maintained high service standards while ensuring a positive and efficient customer experience.",
      ],
      skills: ["Customer Service", "Client Relations", "Issue Resolution"],
    },
    {
      role: "Business Development Specialist",
      company: "American Hole 'n One Insurance",
      date: "February 2025 – May 2026",
      location: "United States · Remote",
      bullets: [
        "Contacted business owners to review and compare employee health benefits, ensuring they were not overpaying for coverage.",
        "Conducted outbound calls to qualify leads, assess current insurance plans, and identify cost-saving opportunities.",
        "Presented alternative coverage options and facilitated comparisons to help businesses make informed decisions.",
      ],
      skills: ["Business Development", "Outbound Sales", "Health Benefits", "Lead Qualification"],
    },
    {
      role: "Recruitment Specialist",
      company: "Renaissance",
      date: "August 2024 – February 2026",
      location: "Dubai, United Arab Emirates",
      bullets: [
        "Managed end-to-end recruitment for Overseas Filipino Workers (OFWs), including sourcing, screening, interviewing, and endorsing qualified candidates to foreign employers.",
        "Coordinated closely with international clients to understand job requirements and qualifications.",
        "Ensured all candidate documents complied with government and deployment requirements (passports, medicals, clearances, contracts).",
        "Acted as a liaison between applicants, agencies, and government offices such as POEA/DMW for processing and compliance.",
        "Provided regular updates to management and clients regarding recruitment progress and candidate status.",
        "Handled concerns and inquiries from applicants professionally, ensuring a smooth and positive recruitment experience.",
      ],
      skills: ["OFW Recruitment", "International Hiring", "Compliance", "Candidate Screening", "POEA/DMW"],
    },
    {
      role: "Sales Representative / Appointment Setter (ISA)",
      company: "YFE Worldwide Logistics, Inc.",
      date: "January 2025 – December 2025",
      location: "Philippines · Remote",
      bullets: [
        "Handled multiple roles strengthening background in customer support, sales, and appointment setting within a logistics environment.",
        "Nurtured inbound and outbound leads, identified customer needs, and converted qualified prospects into scheduled appointments.",
        "Supported customer service and account-related tasks including handling questions, addressing concerns, and explaining services clearly.",
        "Documented interactions accurately in CRM systems and collaborated with internal teams to ensure proper appointment coordination.",
        "Demonstrated a customer-first mindset, strong organization, and reliability in a fast-paced environment.",
      ],
      skills: ["Logistics Management", "Analytical Skills", "Direct Sales", "Client Relations", "Appointment Setting"],
    },
    {
      role: "Data Entry Specialist",
      company: "Jeff Kiesau Agency – American National Insurance",
      date: "February 2025 – September 2025",
      location: "Philippines · Remote",
      bullets: [
        "Worked in a client-facing role supporting insurance policy management and customer service.",
        "Assisted clients with policy inquiries, coverage explanations, and general insurance-related concerns, ensuring clear understanding of options, benefits, and policy terms.",
        "Handled new policy inquiries, renewals, endorsements, and basic policy updates, as well as billing questions and documentation requests.",
        "Supported internal teams by documenting client interactions, updating records in CRM and policy management systems, and coordinating follow-ups.",
      ],
      skills: ["Data Entry", "Customer Service", "Records Management", "Insurance Policy", "CRM"],
    },
    {
      role: "Talent Acquisition Manager",
      company: "Hirey AI",
      date: "November 2023 – May 2025",
      location: "Philippines",
      bullets: [
        "Contributed to the end-to-end hiring process by engaging candidates and supporting client staffing needs.",
        "Served as a key point of contact for both candidates and internal stakeholders, ensuring clear communication throughout the recruitment cycle.",
        "Handled candidate sourcing and screening, conducted initial outreach, confirmed availability, and qualified applicants based on role requirements.",
        "Scheduled interviews, managed follow-ups, and maintained accurate candidate records in applicant tracking systems (ATS).",
        "Supported client and hiring team coordination, ensuring interview schedules, feedback, and next steps were handled efficiently.",
      ],
      skills: ["Recruitment Advertising", "Global Talent Acquisition", "Management", "ATS", "Candidate Engagement"],
    },
    {
      role: "Data Entry Specialist",
      company: "MWORK",
      date: "April 2024 – November 2024",
      location: "Philippines · Remote",
      bullets: [
        "Provided comprehensive customer support and operational assistance by handling inbound and outbound communications through phone, email, and chat.",
        "Managed customer inquiries, account concerns, and service requests with accuracy and professionalism while ensuring timely resolution.",
        "Maintained data entry accuracy and task tracking to keep order-processing workflows organized and efficient.",
        "Supported scheduling, follow-ups, and coordination with internal teams to meet service-level expectations.",
      ],
      skills: ["Data Entry", "Direct Sales", "Automotive Aftermarket", "CRM", "Customer Support"],
    },
    {
      role: "Real Estate Sales — Loan Officer",
      company: "Prime Choice Funding, Inc.",
      date: "January 2024 – September 2024",
      location: "Philippines · Remote",
      bullets: [
        "Guided clients through the loan process from initial inquiry to application and pre-qualification.",
        "Assessed borrower needs and financial profiles, explained available loan options, and helped clients understand requirements and terms.",
        "Handled lead follow-ups and client consultations, gathered and reviewed documentation, and coordinated with internal teams to move applications forward.",
        "Supported pipeline management and CRM documentation, maintaining accurate records and tracking application status.",
      ],
      skills: ["Loan Officers", "Mortgage Lending", "B2B", "B2C Marketing", "Pipeline Management"],
    },
    {
      role: "Administrative Team Lead",
      company: "Morgan & Morgan, P.A.",
      date: "February 2023 – October 2023",
      location: "Philippines",
      bullets: [
        "Served as the first point of contact for prospective and existing clients, handling inbound and outbound calls, emails, and inquiries with professionalism and empathy.",
        "Coordinated scheduling and documentation while handling paralegal document preparation and management.",
      ],
      skills: ["Team Leadership", "Lawful Interception", "Document Management", "Client Communication"],
    },
    {
      role: "Healthcare Specialist",
      company: "UnitedHealth Group",
      date: "August 2022 – February 2023",
      location: "Remote",
      bullets: [
        "Supported daily operations and client engagement by handling inbound and outbound communications through phone, email, and messaging platforms.",
        "Assisted clients with inquiries, service coordination, and follow-ups while ensuring clear, accurate, and professional communication.",
        "Maintained and updated client records, managed data entry in CRM systems, and organized tasks to ensure smooth workflow.",
        "Worked closely with internal teams to coordinate schedules, track progress, and resolve issues efficiently.",
      ],
      skills: ["Healthcare Management", "Data Entry", "Customer Service", "Medical Billing", "CRM"],
    },
    {
      role: "Talent Acquisition Recruiter",
      company: "Sutherland",
      date: "October 2021 – February 2023",
      location: "Philippines · Remote",
      bullets: [
        "Served as a full-cycle recruiter responsible for sourcing, screening, and placing qualified candidates across multiple roles and industries.",
        "Actively identified top talent through job boards, LinkedIn, referrals, and direct outreach, using headhunting strategies to engage passive candidates.",
        "Conducted initial interviews to assess skills, experience, cultural fit, and role alignment before endorsing candidates to hiring managers.",
        "Managed end-to-end recruitment processes including candidate profiling, interview coordination, follow-ups, and offer support.",
        "Partnered closely with clients and internal stakeholders to understand hiring needs, job requirements, and timelines.",
      ],
      skills: ["Recruiting", "Global Talent Acquisition", "ATS", "CRM", "Headhunting"],
    },
    {
      role: "Customer Service Representative",
      company: "AT&T",
      date: "October 2021 – October 2022",
      location: "Philippines",
      bullets: [
        "Handled high-volume inbound and outbound interactions through phone, email, and chat as a customer support professional.",
        "Assisted customers with account inquiries, billing concerns, service issues, and general support requests with accurate, empathetic, and solution-focused assistance.",
        "Maintained strict adherence to company policies, scripts, and service-level agreements with precise documentation in CRM systems.",
        "Effectively de-escalated sensitive concerns and collaborated with internal teams to ensure timely issue resolution.",
      ],
      skills: ["Customer Service", "Billing Process", "Telecommunications", "CRM", "De-escalation"],
    },
    {
      role: "Real Estate Specialist",
      company: "Calltend Inc.",
      date: "December 2020 – January 2021",
      location: "United States · Remote",
      bullets: [
        "Worked as both a Quoter and Business Development Representative (BDR) in real estate.",
        "Generated and qualified leads, conducted outbound cold calls, prepared accurate quotes, and followed up with prospects.",
        "Set appointments for the sales team, developing strong customer service, sales, and relationship-building skills.",
      ],
      skills: ["Real Estate", "Business Development", "Cold Calling", "Lead Generation", "Quoting"],
    },
    {
      role: "Client Management Specialist",
      company: "Amazon FBA Private Label Retailer (Wraith.co)",
      date: "November 2019 – December 2020",
      location: "Philippines · Remote",
      bullets: [
        "Served as the primary point of contact for assigned clients, ensuring strong, long-term relationships through consistent communication and reliable support.",
        "Managed client accounts from onboarding through ongoing engagement, making sure expectations, timelines, and deliverables were met.",
        "Coordinated closely with internal teams to align client needs with operational execution.",
        "Supported sales and growth initiatives by identifying client needs, uncovering opportunities for upselling or service expansion.",
        "Maintained accurate documentation, CRM management, and follow-through across all client interactions.",
      ],
      skills: ["Administration", "Contact Centers", "Administrative Assistance", "Account Management", "CRM"],
    },
    {
      role: "Customer Service Representative",
      company: "VXI Global Solutions",
      date: "March 2017 – December 2018",
      location: "National Capital Region, Philippines",
      bullets: [
        "Provided high-quality customer support in a fast-paced contact center environment, handling inbound and outbound interactions related to account inquiries, billing concerns, and service changes.",
        "Assisted customers with understanding products, plans, promotions, and policies while ensuring accuracy and compliance.",
        "Demonstrated strong problem-solving and communication skills by resolving complex concerns and de-escalating calls professionally.",
        "Managed account updates, payments, cancellations, and retention efforts while identifying opportunities to educate customers.",
      ],
      skills: ["Customer Service", "Email Marketing", "Technical Support", "Sales Processes", "Retention"],
    },
    {
      role: "Skincare Consultant",
      company: "Proactiv",
      date: "February 2018 – November 2018",
      location: "Philippines · Remote",
      bullets: [
        "Handled high-volume inbound and outbound customer interactions, providing professional and empathetic support across account management, billing, subscriptions, and service-related concerns.",
        "Assisted customers with inquiries, payment issues, cancellations, refunds, and account updates while ensuring strict adherence to company policies.",
        "Demonstrated strong problem-solving and de-escalation skills when managing escalated or sensitive concerns.",
        "Accurately documented customer interactions, resolutions, and follow-ups using CRM systems to ensure data integrity.",
      ],
      skills: ["Customer Service", "Management", "Account Management", "CRM", "De-escalation"],
    },
    {
      role: "Customer Service Representative",
      company: "Bluestem Brands",
      date: "January 2014 – September 2014",
      location: "Philippines",
      bullets: [
        "Delivered customer-focused support in a high-volume contact center environment, handling inbound and outbound interactions related to account inquiries, service requests, and billing concerns.",
        "Assisted customers by providing clear explanations of products, services, and policies while ensuring accuracy and compliance.",
        "Effectively managed customer concerns by identifying issues, offering appropriate solutions, and de-escalating situations with professionalism.",
        "Processed account updates, payments, cancellations, and service adjustments while maintaining detailed documentation in CRM systems.",
      ],
      skills: ["Customer Service", "Retail Sales", "Management", "CRM", "Issue Resolution"],
    },
  ],

  education: [
    {
      degree: "Bachelor of Science in Criminology",
      school: "University of Mindanao",
      year: "2010 – 2014",
    },
    {
      degree: "Bachelor of Science in Culinary Arts, Graduate",
      school: "C.L.I.C.K.S Culinary Arts",
      year: "2016 – 2018",
    },
  ],
};
